apiVersion: v1
kind: Service
metadata:
  name: apibike-service
  labels:
    app: apibike
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: apibike